[package]
name = "pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
default = []
diagnostics = []

[dependencies]
rand = "*"
bevy = { version = "0.12" }
bevy-inspector-egui = "*"
bevy_asset_loader = "*"
