[env]
RUST_BACKTRACE = "1"
PKG_CONFIG_PATH_x86_64-unknown-linux-gnu = "/homebrew/alsa-lib/1.2.11/lib/pkgconfig"
LD_LIBRARY_PATH = "/homebrew/libxkbcommon/1.7.0/lib"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = ["--cfg=web_sys_unstable_apis"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
