name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/git
          ~/.cargo/registry
          target          
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dependencies
      run: |
        if [[ ! $(which wasm-pack) ]]; then 
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        fi
        rustup target add wasm32-unknown-unknown
        cargo install wasm-bindgen-cli
    - name: Build
      run: |
        find .
        ./publish.sh
    - uses: actions/checkout@v4
      with:
        repository: 'khanage/khanage.github.io'
        ref: 'main'
        token: ${{ secrets.PAGES_DEPLOYMENT_TOKEN }}
        path: ../khanage.github.io
    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "<>"
